services:

  bie-solr:
    image: ghcr.io/biodiversitydata-se/bie-solr:1.0.3
    #image: sbdi/bie-solr-dev
    environment:
      SOLR_HEAP: 4g
      SOLR_OPTS: "-Dlog4j2.formatMsgNoLookups=true"
    #build:
    #  context: ../bie-solr
    ports:
      - "8983:8983"
    volumes:
      - data_bie_solr:/var/solr

  bie-index:
    image: sbdi/bie-index-dev
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - ./sbdi/data/config/bie-index-config.yml:/data/bie-index/config/bie-index-config.yml
      - data_bie_index:/data/bie-index/data

volumes:
  data_bie_solr:
    #driver: local
    #driver_opts:
    #  type: none
    #  o: bind
    #  device: /data/bie-index/data_bie_solr
  data_bie_index:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/data/bie-index/data"
